# Codebase Patterns

Reusable patterns discovered during development. Read this before starting new work.

## Code Conventions

- Dev loop: `uv venv --python 3.13 .venv` (SDK caps at 3.13; system python may be newer), install `-e ".[dev]"`, gates via `.venv/bin/{ruff,pytest}` (with default parallel test runner `pytest-xdist` `-ra -n auto`); set `QT_QPA_PLATFORM=offscreen` for pytest (from: phase01_core_20260827, 2026-08-27; reconfirmed in phase02_uishell_20260827 with PySide6 6.11.2; xdist enabled 2026-08-28).
- Tiered pytest runs: while iterating use `pytest tests/unit` (fast), full `pytest` (~23 s incl. the smoke subprocess suites; 893 passed + 1 skipped 2026-09-04 — 37 unit files + 5 smoke modules; NOTE one flaky ordering failure `TestRenderTelemetry::test_eta_completes_to_zero_on_last_segment` passes in isolation) is the pre-commit gate per the quality rule below — CI always runs the full suite (from: bead VieNeuTTSApp-e6b, 2026-08-31; counts re-verified 2026-09-04).
- `QT_AUDIO_BACKEND=ffmpeg` in tests needing the real player (CI sets it globally); `QMediaPlayer` has no `resume()` (play() resumes) — consolidated here from the Gotchas audio entry (from: phase03_corefeat_20260827 + ci fix 3ffabd0, 2026-09-03).
- Qt allows ONE QGuiApplication per process and QML ABORTS the interpreter if only a headless QCoreApplication exists — GUI-object-tree assertions in pytest must run in a subprocess (`sys.executable -c` + RESULT: json stdout line) (from: phase02_uishell_20260827, 2026-08-27).
- `setContextProperty` does NOT take ownership of the Python object: anchor it (e.g. `engine._bridge = bridge`) or GC collects it and QML bindings see `null` (from: phase02_uishell_20260827, 2026-08-27).
- QML files should live in one dir and use same-directory `import "."` for the Theme singleton (registered in qmldir); the engine needs `addImportPath(qml_dir)` — bare absolute-path imports are rejected (from: phase02_uishell_20260827, 2026-08-27).
- `findChildren(QObject, name)` returns generic QObject wrappers — read QML-declared properties via `.property("name")`, not attribute access; StackLayout instantiates ALL children, so use currentIndex for visibility, not existence (from: phase02_uishell_20260827, 2026-08-27).
- Wayland blocks QScreen.grabWindow (0×0) without an XDG portal — for "window shows" evidence assert `isExposed()` + live event loop (from: phase02_uishell_20260827, 2026-08-27).
- QML teardown must be DETERMINISTIC: call `_teardown_qml()` after `app.exec()` while the context-property anchors (engine → bridge/controller/playback) are still alive. Interpreter-shutdown global clearing order is arbitrary; when `engine` dies first the surviving QML tree re-evaluates bindings against null and floods ~186–192 "Cannot read property 'x' of null" TypeErrors. The old "harmless post-quit stderr noise" reading was wrong — that noise was this defect (fixed 5a578eb, v0.1.14).
- `QGuiApplication.styleHints().colorScheme()` reports Unknown under offscreen/no-platform → treat as dark (the app's safe default); real light/dark only appear on a live desktop session (from: phase02_uishell_20260827, archived 2026-08-27).
- Quality gate per task: `ruff check .` + `ruff format --check .` + `pytest` must all pass before committing; commit with conventional prefix + `git notes add` task summary (from: phase01_core_20260827, 2026-08-27).
- Ruff excludes `.agents/`, `conductor/`, `*.md` (tooling and frozen planning docs are not app code; ruff 0.16 otherwise formats Python inside Markdown) (from: phase01_core_20260827, 2026-08-27).
- Parallel sub-agents sharing a git index hit `index.lock` occasionally: serialize commits through the orchestrator (retry-after-5s also works); agents run only their scoped tests — the orchestrator runs the full gate before committing; coordinate SHARED UI copy through the orchestrator too — concurrent copy edits caused test ping-pong in phase04 until the final copy pinned all partner phrases verbatim by objectName (from: phase02_uishell_20260827 + phase03_corefeat_20260827 + phase04_streaming_20260827, 2026-08-27).

- QML `var` property signals do NOT fire on in-place array mutation (`samples.push(...)` leaves derived bindings stale) — reassign a fresh array per update so NOTIFY fires (from: phase04_streaming_20260827, 2026-08-27).
- Streaming to UI contract: only NUMBERS cross the Python→QML boundary — Python computes a peak-amplitude envelope (0..1) and emits `levelReady(float)`; raw samples never reach QML (from: phase04_streaming_20260827, 2026-08-27).

- QML Component Libraries & Subfolders: Subfolder components (e.g. `src/vienetts_app/ui/qml/components/`) can be cleanly registered in root `qmldir` with relative paths (`AppCard 1.0 components/AppCard.qml`), or declared via subfolder `qmldir` and consumed via `import "components"` (from: ui_redesign_20260827, 2026-08-27).
- Dynamic Theme Tokens: Theme tokens (`Theme.qml`) bound to a bridge preference (`bridge.effectiveTheme`) should use reactive property bindings rather than static constants, providing instantaneous dark/light updates across all controls without engine or application restart (from: ui_redesign_20260827, 2026-08-27).
- Custom QML ComboBox Delegates: Custom `ItemDelegate` in `ComboBox` popups require `required property var modelData` and `required property int index`, plus `width: combo.width` to ensure popup item clicks and highlights dispatch cleanly without dynamic lookup errors in test suites (from: ui_redesign_20260827, 2026-08-27).
- QML Elevation & Drop Areas: `MultiEffect` (QtQuick.Effects, Qt 6.11) supports `shadowEnabled/shadowColor` but NOT `autoShadowColor`; children funneled through a card's `default property alias` into a ColumnLayout are layout-managed — wrap `DropArea`s in a plain Item or attach inside a Rectangle, never as a direct card child with anchors (from: ui_refine_20260828, 2026-08-28).
- QML Property API Traps: `TextArea` has `lineSpacing` not `lineHeight`; `font.underline` not `underline`; `RowLayout` has no padding properties (use child `Layout.*Margin`); same-directory components resolve implicitly — from inside `components/` import only `".."` for Theme (from: ui_refine_20260828, 2026-08-28).
- Bundled QML Fonts: `FontLoader` sources resolve relative to the QML file — ship TTFs under `ui/qml/fonts/`; a `pragma Singleton` QtObject may own FontLoaders and expose the family via the NOTIFY `name` so `fontFamily` flips system-fallback → bundled family reactively (Be Vietnam Pro, OFL) (from: ui_refine_20260828, 2026-08-28).
- Screenshot Verification Harness: `QQuickWindow.grabWindow()` captures the QML scene WITHOUT macOS screen-recording TCC permission (`QScreen.grabWindow` silently returns empty); drive with FakeController/FakePlayback via `create_app` factories, tab/theme/state scripted with QTimer settles (from: ui_redesign_20260827 + ui_refine_20260828, 2026-08-28).
- Audiobook seam (one engine, two controllers): route worker results through an ATTACHABLE listener on AppController (`attach_synthesis_listener` / `submit_stream_for_listener`); submit refuses while busy so attach+submit is atomic w.r.t. job completion, and the listener MUST detach inside its done/error handler. Never build a second InferenceWorker — two workers means two model loads (~800 MB each) (from: audiobook_epub_20260828, 2026-08-28).
- Atomic audio-file writes must keep the target extension (`x.part.wav`), because soundfile infers the container format from the path suffix — `x.wav.tmp` raises "No format specified" (from: audiobook_epub_20260828, 2026-08-28).
- Hidden StackLayout tabs have UNSETTLED bindings: `property("visible")` reads stale values until the tab becomes current — activate the tab + processEvents before asserting its UI state in drivers; delegate-order from childItems() walks is arbitrary, so select delegates by `modelData` and count conditional children by their `visible` property; QML data fakes need real NOTIFY `@Property` members (plain Python attributes read as undefined). `QMetaObject.invokeMethod(item, "click")` works for Controls, "toggle" does not (from: audiobook_epub_20260828, 2026-08-28).
- Keyboard focus ring for a11y: `activeFocus && (focusReason === Qt.TabFocusReason || focusReason === Qt.BacktabFocusReason)` displays focus visual rings exclusively for keyboard navigation while keeping pointer clicks clean and free of spurious outlines (from: ui_refine_20260828, 2026-08-28).
- VoicePicker / ComboBox non-circular reactivity: direct `currentIndex` binding to a controller property that can be mutated by user selection creates circular binding loops; use imperative sync on `Component.onCompleted` plus a declarative `Connections` handler on the changed signal instead (from: ui_refine_20260828, 2026-08-28).
- QML animation loops: drive with a ~33ms Timer that STOPS itself once the animation settles (all values at target) and restarts on the next change — a always-running repaint loop burns CPU at idle; glide/lerp toward targets inside the tick, never jump (from: bead-driven waveform work a6r/yi5/56h, 2026-08-29).
- Every byte/count property exposed to QML must be `qlonglong`, never Qt `int` (32-bit): the linux-x64 managed-CUDA manifest needs 7,923,412,460 bytes, which raised `OverflowError` inside a SettingsTab binding and unwound through `ShellBridge.setCurrentTab` → `currentTabChanged.emit()` into the crash handler. Format multi-GB labels as pre-formatted strings — QML number-to-text renders them as "7.92341e+09" (from: commit 5a578eb, 2026-09-10).
- Tall-tab layout rule: a single stacked content column past the viewport buries the primary CTA behind scroll (ParagraphTab was 948 px tall against a 652 px viewport → CTA 208 px below the fold). Split mutually exclusive workflows into segmented modes (`ModeTabs`) over separate surfaces and move global actions into a docked bar (`SynthesisBar`); `PageShell.stretch` lets a populated list fill the page instead of leaving a void (from: commit 0d684ba, 2026-09-10).
- Localize catalog metadata at DISPLAY time: VoicePicker maps region/gender/style tags per locale (region → "Miền …", translated gender/style with disambiguation comments) so a southern male voice stops rendering two identical "Nam" chips and the English UI never shows Vietnamese catalog metadata while the catalog model itself stays untouched (from: commit 0d684ba, 2026-09-10).
- Text-pin rule for custom control skins: the smoke/unit suites read the CONTROL's own `text` property (`denoiseCheck.property("text")`), so a custom `contentItem` must MIRROR `control.text` (bind to it, or write back through the control) rather than replace the property's value — a skin that only renders the label internally reads back empty to every assertion (from: ui_refine_20260828, archived 2026-09-21).
- Inline `component` templates declared inside a tab are trap-prone: `parent.parent.label`-style lookups and default-property aliasing silently bind to the wrong object and break on the next refactor — declare explicit rows/items instead, and keep reusable pieces in `ui/qml/components/` registered through `qmldir` (from: ui_refine_20260828, archived 2026-09-21).
- One skin per control, no per-tab restyling: every button goes through `AppButton`, every combo through `AppCombo`, voice lists through the shared `VoicePicker` (tabs contain ZERO inline Button backgrounds), and `AppIcon`'s Canvas switch (kind string → 20×20 vector) is the only icon source — restyling is then a single-file change and the smoke `objectName` contracts survive UI extraction (from: ui_refine_20260828, archived 2026-09-21).
- Responsive tab posture: wrap tab contents in a `ScrollView` with `contentWidth: availableWidth` and a centered max-width column (`Math.min(840, root.availableWidth - Theme.spacingLg * 2)`) so the same layout is usable from the 640×420 minimum window to 1440×900+ without horizontal clipping; a `Repeater` nested in a `ColumnLayout` needs its delegates wrapped in a real control with an explicit `Layout.fillWidth`, or the layout collapses (from: ui_redesign_20260827, archived 2026-09-21).
- CheckBox strict-binding write-back is SAFE (and preferred): a strict `checked: controller.flag` binding survives the C++ `toggle()` (which does not break the binding) and `onToggled:` syncs the controller, with the NOTIFY re-evaluation keeping the two consistent — do not replace it with imperative sync just because the property is written from QML (from: audiobook_epub_20260828, archived 2026-09-21).

## Architecture

- `Vieneu` is a factory FUNCTION (`Vieneu(mode="v3turbo", backend=..., precision=...)`), not a class; kwargs pass through to the engine. Full confirmed contract: `docs/spike-report.md` §0 (from: phase01_core_20260827, 2026-08-27).
- Engine ownership: exactly one `TTSEngine` (lazily initializes its Vieneu) owned by one `InferenceWorker` QThread; requests serialize through its queue; cancel is cooperative between stream chunks (from: phase01_core_20260827, 2026-08-27).
- Voice keys: `list_preset_voices()` → `[(label, voice_id)]`; **voice_id (element [1])** is the key for `infer(voice=...)`; labels encode gender·region·style for North/Central/South grouping (from: phase01_core_20260827, 2026-08-27).
- Offline bundling: portable `HF_HOME` + `HF_HUB_OFFLINE=1` with pre-seeded cache; the codec repo is NOT dir-loadable via the public API; minimal CPU bundle via `scripts/fetch_models.py` (327 MB, SHA256 manifest) (from: phase01_core_20260827, 2026-08-27).
- ONNX precision→subfolder map: int8 → `onnx_int8`, fp32 → `onnx_update` (NOT `onnx/` as the plan sketch assumed) (from: phase01_core_20260827, archived 2026-08-27).
- `snapshot_download(..., local_dir=..., allow_patterns=[...])` writes a `.cache/huggingface` metadata dir INSIDE the bundle — always exclude it from manifests/hashes (from: phase01_core_20260827, archived 2026-08-27).
- Streaming contract: `infer_stream` yields float32 1-D mono chunks of variable size (~15360–96000 samples); concatenate for full audio. It carries its own sampling defaults (temperature=0.8, top_k=25, top_p=0.95), different from `infer` (temperature=0.4, top_k=50) (from: phase01_core_20260827, archived 2026-08-27).
- vieneu voice persistence: `save_voices(path)` writes ALL voices; there is NO custom-path LOAD api (init always reads site-packages assets). App-owned persistence = save to `<app data>/voices/voices.json` + merge-back into `tts._preset_voices` at engine init; `add_voice` must always pass `save=False` (from: phase03_corefeat_20260827, 2026-08-27).
- vieneu preset catalog is model-free: read `Path(vieneu.__file__).parent/assets/voices_v3_turbo.json` (20 presets; description format `gender · region · style` — middle token is the region for N/C/S grouping). Asset shape: top-level meta/default_voice/presets (from: phase03_corefeat_20260827, 2026-08-27).
- EPUB spine href normalization: EPUB spine hrefs are percent-encoded and relative to the OPF directory — apply `urllib.parse.unquote`, normalize forward slashes, and prefix the OPF directory; nav/cover documents are identified and filtered via `properties="nav"` and non-blank text extraction checks (from: audiobook_epub_20260828, 2026-08-28).
- Persist derived data as a sidecar JSON next to its source artifact (`ch_XXXX.waveform.json` beside `ch_XXXX.wav`): write atomically, treat absent/corrupt as a cache miss, and recompute ONCE from the source — deferred off the load path via `QTimer.singleShot(0, ...)` with a state-unchanged guard — for artifacts created before the sidecar existed (from: bead-driven waveform work a6r/yi5/56h, 2026-08-29).
- Shared-subprocess QML smoke drivers: run a LIST of scenarios per subprocess (one QGuiApplication, fresh engine+fakes per scenario via `create_app`'s instance() reuse, deterministic `engine.deleteLater()` + `gc.collect()` + `processEvents()` between scenarios); the driver prints one `RESULT:` mapping scenario→out and the pytest side rebinds `result = results["<scenario>"]` between assertion blocks — merging N launches into one saves ~1 s each (from: bead VieNeuTTSApp-6ex, 2026-08-29).
- QGuiApplication-level state leaks ACROSS engines in one process: `create_app` installs its language translator on the app, and destroying the engine does NOT remove it — sequential in-process "fresh boot" phases must `app.removeTranslator(engine._translator)` before teardown or a vi-boot phase renders English from the previous en phase (from: bead VieNeuTTSApp-6ex, 2026-08-29).
- PyInstaller frozen-build layout contract: data trees (`vieneu`/`vieneu_utils` voice+sample assets, `sea_g2p`'s ~60 MB Rust dictionary, `kaldi_native_fbank` dylibs) must land INSIDE the frozen `vienetts_app` package at the same relative layout the source tree uses — then `Path(__file__).parent`-relative resolution (e.g. `QML_DIR`) needs zero frozen-mode code paths. Lazily-imported engine submodules (`vieneu.factory` imports inside functions) require `collect_submodules` hiddenimports or every infer dies with ENOENT on `sea_g2p.bin`; torch/transformers are EXCLUDED deliberately to keep the CPU build torch-free (from: release-pipeline work 9bf0ce8, 2026-08-29).
- GUI-thread offload for one-shot heavy ops (`ui/bg_ops.py`, `ui/chapter_persist.py`): run the callable as a `QRunnable` on the global Qt thread pool and marshal the result back through a queued signal; controllers take an injectable `bg_runner` (production = thread pool, tests = `run_sync`) for deterministic inline completion. The callback re-validates identity (book id) before touching state — the same straggler-guard discipline as worker signals (from: beads VieNeuTTSApp-12k/dfe/00w, 2026-09-02).
- Streaming buffer economics: on the audio hot path hand out zero-copy chunk views, grow worker buffers by doubling, and use an offset-based `StreamIODevice` with amortized compaction — never per-chunk full-array copies (from: commit 47e7813, 2026-09-02).
- Artifact-first synthesis (v0.1.4, bead-driven, no track): the worker writes validated 48 kHz mono WAV incrementally via `IncrementalArtifactWriter` (`core/artifacts.py`, `<job>.part.wav` → atomic `os.replace` promote) and feeds live preview through `BoundedPcmTransport` (`core/pcm_transport.py`, 2 s / 384 KB cap, 150 ms prebuffer) — no duration-sized RAM arrays; both replay and export read the artifact (from: commits in v0.1.4 release, 2026-09-03).
- Job-contract routing (v0.1.3, bead-driven, no track): immutable job values (`core/jobs.py`: SynthesisJob/JobProgress/JobChunk/JobTerminal, incl. audition lane) admitted via thread-safe FIFO (`workers/job_queue.py`, per-ID/per-owner cancel); worker terminals are job_id-tagged and the controller routes by ID, dropping stale deliveries (from: commit 6a17ad6, 2026-09-03).
- Pinned model baseline (v0.1.3, bead-driven, no track): `core/official_model_manifest.py` is the frozen allowlist (backbone + codec repos, revisions, file sizes + SHA-256); `core/model_manager.py` installs staging-only with resume, free-space preflight, atomic promote, and Windows MAX_PATH/long-path handling; `scripts/fetch_models.py` derives everything from the manifest (from: commits d0d6298/e371937/83601fa, 2026-09-03).
- WSOLA reading speed (v0.1.5, bead-driven, no track): `Settings.speed` [0.5, 2.0] + `silence_p` [0.0, 2.0] validated in `core/models.py`, applied as engine infer kwargs + NumPy WSOLA post-stretch in `core/audio.py`; silent generate-then-replay is the default (`live_preview=False` in Settings) with the preview toggle routing through the bounded transport (from: commits e131631/882fa17, 2026-09-03).
- Cancellation race discipline (v0.1.7, bead-driven, no track): lock-tracked `_cancel_requested_ids` in `InferenceWorker` + early abort check before PCM-transport writes (`_emit_audio_chunk`) + controller teardown that resets busy/job state even with no active job; QML action buttons show live queued/cancelling states (from: v0.1.7 release, 2026-09-06…10).
- Managed CUDA runtime (v0.1.11, bead-driven, no track): `core/cuda_runtime.py` + pinned records in `core/cuda_runtime_manifest.py` (rendered by maintainer-only `scripts/lock_cuda_runtime.py`); opt-in Settings download into the per-user data dir, verified before install, offline after; the app never invokes pip or executes locally discovered Python envs; `torchAvailable` probe is lazy/off-thread so cold start stays model-free (from: commits bf195d8/38ae2f8, 2026-09-06…10; supersedes the brief v0.1.9 `-cuda` bundles).
- In-app update checks (v0.1.6, bead-driven, no track): stdlib-urllib GitHub Releases query in `core/updates.py` with platform-aware asset matching (variant-aware during the `-cuda` era), silent check after startup + hourly recheck, Settings badge + manual check button, frozen version stamping with release-time assertion (from: v0.1.6 release, 2026-09-06…10).
- Batch synthesis queue (v0.1.7, bead-driven, no track): `ui/batch_controller.py` + `BatchQueueCard.qml` — off-thread import with oversize guard, smart single-vs-multi drop routing, sequential auto-run via `submit_stream_for_listener(kind="bulk")`, per-file auto-export with collision-safe suffixing, failure-continue, chunk-artifact lifecycle cleanup (from: v0.1.7 release, 2026-09-06…10).
- Mini Audio Studio op stack (v0.1.13, bead-driven, no track): non-destructive gain/fade/speed/gap/normalize/trim ops in `core/studio.py` + `StudioTab.qml`, per-segment re-synthesis with 10 ms crossfade, feeder "Studio…" buttons on Text/Paragraph/Audiobook tabs (from: commits 0f11649/55903d7, 2026-09-06…10).
- Pro-audio Studio deck (v0.1.14, bead-driven, no track): renders/exports run off the GUI thread behind `studioBusy` + per-op spinners with stale-GENERATION guards (in-flight renders are discarded when the project or op stack changes); waveform overview bands normalize against the dry-project peak so Gain/Normalize visibly scale the deck and Undo restores amplitude; Undo/Reset halts obsolete playback, recomputes the op stack, resyncs rack sliders, and auto-plays the updated mix (from: commits 55903d7/45138a3/3290961, 2026-09-10; extends the `bg_ops` straggler-guard discipline).
- Paragraph tab mode composition (v0.1.14, bead-driven, no track): `ModeTabs` segmented switch over mutually exclusive `DocumentEditorCard` vs queue surfaces plus a docked `SynthesisBar`; `BatchQueueCard` is a list-only queue panel whose errors route to the visible notice (they were rendered nowhere before); VoicePicker owns its model so the dead `buildFlatModel` copies in Text/Settings are gone (only AudiobookTab still injects one); a THIRD mode ("Phụ đề (SRT)", 2026-09-14) composes the subtitle card into the same switch, and a mode change keeps the page scrolled in place (`e255027`) (from: commit 0d684ba, 2026-09-10; extended 2026-09-14).
- Settings card split (v0.1.14, bead-driven, no track): Engine / Managed CUDA runtime / Model source are separate top-level cards; verbose CUDA guidance lives behind a `Details & diagnostics` disclosure (collapsed by default; auto-expands for in-flight/failed installs, unusable driver, or a prior scan; a manual collapse sticks); driver commands are monospace rows sharing a `controller.copyText` seam, and all 21 smoke-contract objectNames are preserved (from: commit 3eb6c90, 2026-09-10).
- Subtitle dub/transcript studio (2026-09-14, bead-driven, no track): three PURE core layers behind one QML controller seam — `core/subtitles.py` (cue model: no Qt, no disk policy), `core/align.py` (fit planning only), `core/subtitle_project.py` (workspace store + streaming renderer) — surfaced by `ui/subtitle_controller.py` as the `subtitleController` context property and composed as the third Paragraph-tab mode ("Phụ đề (SRT)") in `SubtitleCard.qml`. Two policies: `dub` treats the SRT clock as master (rate-compress an overlong take up to `rateCap`, push later cues on overflow) and `transcript` treats the voice as master (never compress; cap inter-cue pauses). Renders reuse the AppController synthesis-listener seam (`attach_synthesis_listener` / `submit_stream_for_listener`) exactly like Audiobook/Batch — one worker, one model, no second load (from: commits 2068d8d/617cfdc, 2026-09-14).
- Streaming track render + fingerprint cache (2026-09-14): `SubtitleTrackRenderer` writes the mix clip-by-clip to `PCM_16` `track.wav` — a two-hour track is ~690 MB on disk instead of a ~1.4 GB float array in RAM, and every reader goes through `read_wav` which converts back — and `render_fingerprint()` hashes everything that changes the audio, so an unchanged fingerprint reuses the cached track instead of re-synthesizing (NFR-A1). Same discipline as the audiobook chapter cache (from: commit 2068d8d, 2026-09-14).
- Subtitle speech-unit grouping (2026-09-14): `core/align.speech_units` groups cue indices into synthesis units; a sentence-terminator test ALONE would merge a whole film because subtitle cues frequently omit terminal punctuation, so `UNIT_MAX_CHARS` (220) and `UNIT_GAP_MS` (600) guards bound units to sentence size; merged unit audio splits back across its cues proportional to text length. The aligner's `MIN_RATE`/`MAX_RATE` mirror the studio's reading-speed bounds so any rate the planner emits is renderable (from: commit 2068d8d, 2026-09-14).
- Subtitle workspace id safety (2026-09-14): `project_id_for` derives a 16-hex-char id from source name + spoken text (same content → same id) and `SubtitleProjectStore` refuses any caller-supplied id that does not match `^[0-9a-f]{16}$`, so an id can never become a path segment with `..` or separators; the store reuses the app's atomic-JSON-write + WinError-32 retry posture (`REPLACE_LOCK_ATTEMPTS`) and `PROJECT_VERSION` guards loads against an incompatible schema (from: commit 2068d8d, 2026-09-14).
- Studio redesign + UX refinement (v0.1.15/v0.1.16, bead-driven, no track): the Studio tab is organized around a PINNED transport dock (play/pause/seek + timecodes + previews never scroll away) — the same tall-tab lesson as the Paragraph `SynthesisBar`, now applied for Studio; `StudioTab.qml` was decomposed into `StudioRackModule`/`StudioParamRow`/`StudioClipRow` reusable components (1757 → 1398 lines) with `AppCard` gaining `clickable`/`cardHovered`/`cardClicked` for whole-card tap targets and `AppNumberField` supplying clamped, two-way-synced precise entry beside every FX slider. State-truthfulness is the recurring theme: the rack readout folds gain sums and speed multipliers to match the rendered mix and applies in place rather than stacking duplicate ops, clip auditioning publishes the actually-playing clip so the dock and highlight agree, and the transport status dot is neutral when idle / accent when playing (was green when idle — an inverted convention). Destructive actions (cut range, reset) are danger-styled and confirmed, and busy buttons keep their label while spinning so wrapping toolbars do not reflow. All tested `objectName` contracts survived the extraction (from: commits bc8b182/156c82f/d5b2529, 2026-09-15/16).

- Qwen multi-engine track (2026-09-20/21, `qwen_multiengine_20260920`): ONE capability table is the truth for engine profiles — `core/engine_profiles.py` declares `vieneu` | `qwen_custom_0_6b` | `qwen_base_0_6b` with their voices source, languages, devices, cloning requirements and runtime kind; `EngineState.qml` is its single UI derivation (voices/language/readiness/cloning) and `AppController.submission_context_for()` is the single submission gate that builds a validated `SynthesisContext` (or refuses with the capability table's own message). Adding a branch that reads profile fields anywhere else re-introduces the drift this table exists to prevent (from: commits 88feee2/173c435/198ffac, 2026-09-20/21).
- Isolated Qwen model host (2026-09-20/21): `workers/qwen_host.py` is a separate interpreter that owns exactly one resident checkpoint and speaks the framed `core/qwen_protocol.py` contract; `core/qwen_engine.py` owns its lifecycle — spawn (sanitized offline env, `CREATE_NO_WINDOW` via the patchable `IS_WINDOWS` seam), hello+load handshake with cached capabilities, streaming with per-frame timeouts, cancel that escalates request → terminate → kill, and reaping on every failure path with a LAZY restart on the next job. Two semantics worth remembering: the pinned runtime cannot interrupt a live `generate_*` call, so a host that does not settle is force-cancelled and the parent still reports `QwenEngineCancelled` (never a crash), and a dead host's pipe must never kill the app — `_write_frame_safely` blocks SIGPIPE for the writing thread because `_restore_default_sigpipe()` sets `SIG_DFL` process-wide when the app's own stdout is a pipe (from: commits c348855/328baf5, 2026-09-21).
- Verified managed installs (2026-09-20/21): the Qwen runtime (wheels) and models (file trees) install through the SAME staging → verify → atomic-promote posture as the CUDA runtime and the VieNeu baseline — every file checked against a pinned manifest (`size_bytes` + `sha256`) before promotion, free-space preflight, `install_from_offline_pack` accepting exactly the manifest's layout so an offline pack cannot smuggle a different build, and shared model files stored ONCE (`<root>/shared/`) and reused across profiles (~683 MB of the two 0.6B profiles). The Qwen stack never enters `pyproject.toml`/`uv.lock` or the frozen bundle (spec excludes derived from the host's deferred imports, `--qwen-host` re-dispatch) (from: commits dc12914/a03f365/e92cc0f, 2026-09-20/21).
- Engine-stamped provenance (2026-09-20/21): every submission carries an immutable `SynthesisContext` (`core/synthesis_context.py` — profile, language, speaker/clone, model revision) that travels with the job, the artifact and the cache key; `context_matches` is the conservative cache rule and `same_engine` the looser rule for an EXPLICIT Studio re-synthesis, and a payload with no recorded identity counts as VieNeu (every pre-multi-engine render was). Studio clips expose `profile`/`profileLabel`/`language`, refuse a mismatched re-synthesis with the required profile named, and arm a one-click switch that consumes the offer; the armed splice is disarmed on every non-success path (from: commits 5a49a2d/24561d5, 2026-09-20).
- Profile-scoped voice clones (2026-09-20): `core/voice_profiles.py` keys clones by engine profile (a Qwen clone is never offered to VieNeu and vice versa), stores the reference clip + transcript + consent, and the capability table decides which requirements apply (transcript needed for Qwen Base, reference denoise only for the bundled VieNeu engine); enrollment is stamped with the active profile so a clone stays attributable after a switch (from: commits 0dd67f4/d82c6a4/c9442d9, 2026-09-20/21).
- Two-tier engine validation (2026-09-21): deterministic fake-host coverage is the mandatory tier — `tests/unit/qwen_host_fake.py` is a REAL child process speaking the real protocol, and the consolidated subprocess scenarios in `tests/smoke/test_e2e_flows.py` drive the real controller/worker/QML against it (ready install → profile switch → synthesis → enrollment → Studio guard → cancel → crash → shutdown). The real-model tier is opt-in and separate: `scripts/qwen_release_smoke.py` consumes pre-provisioned verified packs through the app's own installers and the app's own host, and `.github/workflows/qwen-runtime-smoke.yml` runs it per matrix cell — ordinary CI downloads nothing, so a flow that is only covered by the opt-in tier is effectively untested on every push (from: commits 328baf5/9d52d1b, 2026-09-21).

## Gotchas

- Subprocess QML drivers built via textwrap.dedent: keep `\n` escapes literal inside nested strings/docstrings, and never let a line hit column 0 — dedent then no-ops into IndentationError in every subprocess (from: phase04_streaming_20260827, 2026-08-27).
- Subprocess GUI drivers using the REAL worker must call `shutdown()` before quitting — teardown aborts (rc=-6) otherwise (from: phase04_streaming_20260827, 2026-08-27).
- Hosts exposing ZERO audio output sinks (pipewire-less offscreen) make probe=False the DEFAULT path — playback-flow tests must inject `audio_probe=lambda: True`; assert the export-only posture explicitly rather than assuming device presence (from: phase04_streaming_20260827, 2026-08-27).
- Cancel-before-worker-pickup drains the queue silently and `busy` sticks True forever — await positive evidence of processing before cancelling in tests (from: phase04_streaming_20260827, 2026-08-27).
- Inside a NON-current hidden StackLayout tab offscreen, mid-session side effects (`historyCount`, edge-handler effects) may not run even though binding VALUES propagate — assert such state only while the tab is current/post-settled (extends the visibility rule above) (from: phase04_streaming_20260827, 2026-08-27).
- Qt SpinBox `displayText` renders through the HOST QLocale — the decimal separator follows system locale (`vi_VN` → comma) regardless of LANG; normalize separators before cross-machine string asserts (from: phase04_streaming_20260827, 2026-08-27).
- macOS reports `ru_maxrss` in BYTES (Linux: KB) — divide by 1024² for MB when comparing memory evidence across hosts; measure BOTH ru_maxrss and ps-sampled current RSS (from: phase04_streaming_20260827, 2026-08-27).
- `bd close --continue` AUTO-ADVANCES the next molecule step to in_progress — if premature, reset with `--status open`; real-model chunk counts vary run-to-run (codec adaptive buffering), never assert exact counts/timings against the live model (from: phase04_streaming_20260827, 2026-08-27).

- QML signal-handler parameters (`mouse`, `key`) are injected ONLY into the handler scope — a named helper called from the handler cannot see them (`ReferenceError: mouse is not defined` at click time, not load time, so the bug ships silently); write handlers as arrow functions with formal parameters (`onClicked: (mouse) => ...`) — Qt 6 deprecates implicit parameter injection anyway (from: bead-driven waveform work a6r/yi5/56h, 2026-08-29).

- SDK sample rates differ by function: `infer`/`infer_stream` → float32 mono @ 48 kHz; `denoise` → float32 mono @ **44.1 kHz** (from: phase01_core_20260827, 2026-08-27).
- `add_voice(save=True)` persists into **site-packages** by default — the app must redirect via `save_voices(path=<app data dir>)` (from: phase01_core_20260827, 2026-08-27).
- Qt cross-thread signals are queued to the receiver thread: tests/headless code must pump `QCoreApplication.processEvents()` while waiting (from: phase01_core_20260827, 2026-08-27).
- coverage.py cannot trace PySide6 QThread-run code (C++ threads) — keep logic in directly callable methods and test those synchronously (from: phase01_core_20260827, 2026-08-27).
- `Vieneu(backend="torch")` on a torch-free install raises `ModuleNotFoundError` — always surface an actionable "install [gpu] extra or switch to onnx" message (from: phase01_core_20260827, 2026-08-27).
- ONNX arena memory grows with the largest workload and is never returned to the OS. RESOLVED for streams (phase04): app-level chunked dispatch (`split_text_for_streaming`, 512-char segments via `infer_stream_chunked`) holds long-doc RSS at ~1.12 GB plateau vs <2 GB budget (AC-5, bead VieNeuTTSApp-u5c closed); interactive use stays ~766 MB. NON-stream path RESOLVED 2026-08-31 (bead VieNeuTTSApp-8jm closed): `_process_infer` no longer makes one whole-document `engine.infer` call — it dispatches `split_text_for_streaming` segments so each SDK call is bounded by the same mechanism (from: phase01_core_20260827, 2026-08-27; updated 2026-08-31).
- `sf.write` to an in-memory `BytesIO` needs explicit `format="WAV"`; and `TTSEngine.sample_rate`/`.backend` must raise before init — reading properties must never trigger the lazy model load (from: phase01_core_20260827, archived 2026-08-27).
- Docker Desktop image pulls can hang silently with no error output — compare `docker images` vs `docker ps` to distinguish pull-hang from container-run; kill early rather than waiting (from: phase01_core_20260827, archived 2026-08-27).
- PySide Slot return values: `@Slot(str, bool)` declares an OVERLOAD (str, bool), not a bool return — a QML one-arg call then fails with "Insufficient arguments". Returns are `@Slot(str, result=bool)` / `@Slot(str, result=str)` (from: phase03_corefeat_20260827, 2026-08-27).
- QtMultimedia offscreen: `QAudioOutput` construction deadlocks under pytest fd capture (pipewire devicemonitor probe) — `QT_AUDIO_BACKEND=ffmpeg` in tests needing the real player; `QMediaPlayer` has no `resume()` (play() resumes); enum str() is "PlaybackState.PlayingState" — map via `.name` or split (from: phase03_corefeat_20260827, 2026-08-27).
- Qt6 QML dialogs: FileDialog has no `folder` (Qt5 name) — set `currentFolder`, imperatively before open(). Declaring FileDialog/FolderDialog offscreen is harmless; only opening it is unreliable. Expose each dialog's logic as a QML root function (importPath/selectClip/setOutputDir) — the tested seam `python -c` drivers invoke via `QMetaObject` with `Q_ARG("QVariant", ...)` (QML function args are QVariant in the metaobject) (from: phase03_corefeat_20260827, 2026-08-27).
- QML file URLs → local paths: `QUrl.toLocalPath()` can leave a leading slash before Windows drive letters (`/C:/...`), silently breaking path joins and file/audio APIs — normalize after conversion and route EVERY QML-side file URL through one `toLocalPath` helper; this bit twice in one day (all five tabs, then audiobook export-all) because each tab had its own inline conversion (from: commits 3dbf784 + 2c211d2, 2026-08-29/31).
- Windowed `.exe` has `sys.stdout=None`: redirect stdio to devnull (utf-8/replace) at GUI/`--smoke`/engine-init entry so packaged builds can download + synthesize (from: commit 184b600, 2026-09-03).
- Windows file-lock discipline: retry-bounded `os.replace`/`shutil.copyfile` on WinError 32 (artifact writer, settings, voice persist, exports) with a timestamped sibling fallback (`<stem>_<ns>.wav`) so audio is never dropped; stop playback before preview overwrite; `release_retired_artifacts` suppresses OSError (from: v0.1.8 release, 2026-09-06…10).
- Windows release-tooling traps: `Compress-Archive` fails past 2 GB — zip via streaming tar; pwsh cannot parse backslash continuations — run torch-install steps under `shell: bash` (from: commits c114bf8/0006234, 2026-09-06…10).
- One path helper for everything: route EVERY QML file URL + dropped path through `core/paths.py` (QUrl forms, percent-decoding, quote-stripping, extended-length/UNC, reserved names) — the toLocalPath lesson repeated with importers/exports before the helper existed (from: v0.1.8 release, 2026-09-06…10).
- Crash diagnostics for windowed builds: global `sys`/`threading` excepthooks in `crash.py` → timestamped `logs/crash.log` (OS/arch/runtime/GPU/thread/traceback) + native `MessageBoxW` fallback since there is no console (from: v0.1.8 release, 2026-09-06…10).
- A workflow `jobs.<id>.if:` may only read `github`/`inputs`/`needs`/`vars` — naming `matrix` there makes GitHub reject the WHOLE file ("Invalid workflow file", a 0 s run) and the workflow can never be dispatched until it is fixed; enforce a per-dispatch selection by shrinking the matrix in a `plan` job (`matrix: ${{ fromJSON(needs.plan.outputs.matrix) }}`) so an unselected cell never creates a job (from: qwen_multiengine_20260920 CI fix, 2026-09-21).
- `os.kill(pid, 0)` is NOT a liveness probe on Windows: CPython maps every signal but `CTRL_C_EVENT`/`CTRL_BREAK_EVENT` onto `TerminateProcess`, so "is it alive?" KILLS it — and keeps answering True while any handle to the exited process is open. Route every pid probe through `core/processes.process_alive` (`GetExitCodeProcess` + `STILL_ACTIVE` on Windows) (from: qwen_multiengine_20260920 CI fix, 2026-09-21).
- Closing an anonymous-pipe read end while another thread is blocked in `ReadFile` on it hangs on Windows (`CloseHandle` waits on the pending synchronous read) — so the thread that reads a pipe must close it, and readers must be joined before their streams are closed; a frame-driven exit (shutdown, fatal) leaves exactly that blocked reader behind, an EOF-driven one does not (from: qwen_multiengine_20260920 CI fix, 2026-09-21).
- Windows `CreateProcess` caps the WHOLE command line at ~32 KB: a GUI driver handed to `python -c` fails with `WinError 206 The filename or extension is too long` once it grows past that (a 50 KB e2e driver does); write the driver to a file and run the file — and set `PYTHONPATH` yourself, because script mode drops cwd from `sys.path` (from: qwen_multiengine_20260920 CI fix, 2026-09-21).
- Child processes that print non-ASCII: Windows encodes a PIPED stdout with the ANSI code page, so `print("Ngọc Anh")` dies with `UnicodeEncodeError: 'charmap'` — export `PYTHONIOENCODING=utf-8` (and decode with `encoding="utf-8"`); `import resource` also does not exist on Windows, so RSS/limits need a psapi `GetProcessMemoryInfo` branch (from: qwen_multiengine_20260920 CI fix, 2026-09-21).

## Performance evidence patterns

- Timing events use monotonic offsets from a trace start; distinguish direct
  engine TTFC, controller receipt, transport append, sink pull, and audible
  loopback latency.
- Record both sampled current RSS and monotonic peak RSS, with exact byte
  units at the API boundary.
- Benchmark records identify built-in corpus entries by ID and SHA-256 only;
  never serialize user text, voice names, paths, hostnames, usernames,
  serials, UUIDs, or environment variables.
- Run timing-sensitive suites serially. Keep raw JSONL samples and compare
  medians, p90/p95, and MAD instead of best-of-N results.
- Report direct-engine and production-path claims separately; unsupported
  frame, real-sink, and audible-TTFA metrics remain explicitly unsupported.
- `app.aboutToQuit.connect(controller.shutdown)` binds the method AT CONNECT TIME — post-connect monkeypatches never fire; wrap before connecting in tests (from: phase03_corefeat_20260827, 2026-08-27).
- Document importer error surfaces vary by library and failure mode: pypdf raises different exception types per failure mode (catch broad + chain cause); python-docx raises `PackageNotFoundError`; `extract_text()` may return `None` — coerce with `or ""` (from: phase03_corefeat_20260827, 2026-08-27).
- `tests/fixtures/` is NOT covered by the ruff excludes — fixture generator scripts must pass lint/format like app code (from: phase03_corefeat_20260827, 2026-08-27).

## Testing

- Worker/engine tests use injectable fakes: `TTSEngine(factory=lambda **kw: FakeVieneu())`; `detect_hardware(probe=..., system=..., machine=..., nvidia_smi=...)` for the §6.1 matrix (from: phase01_core_20260827, 2026-08-27).
- CLI tests call `main([...], engine_factory=...)` for exit codes + WAV verification without loading the model (from: phase01_core_20260827, 2026-08-27).
- Memory checks need BOTH `ru_maxrss` (monotonic peak) and current RSS via `ps -o rss= -p PID` — peak alone cannot distinguish a leak from arena growth (from: phase01_core_20260827, archived 2026-08-27).
- CI smoke entry: `python -m vienetts_app --smoke "Xin chào" --voice Adam -o out.wav` (AC-3); engine readout comes from the detector's capability view. Since Phase 2 (FR-2.1) `--smoke` is OPTIONAL — no args launches the GUI, and CLI-contract tests inject a `gui_runner` instead of relying on the usage-error path (from: phase01_core_20260827, 2026-08-27; updated phase02_uishell_20260827).
- QML test driving: Repeater delegates are incubated objects with a visual parent but NO QObject parent — `findChildren(QObject, name)` never sees them; walk `contentItem().childItems()` recursively. Button clicks work via `QMetaObject.invokeMethod(item, "click")`; ComboBox `activate()` is QML-side only — emit the bound `activated(i)` signal instead. SpinBox `text` is unreadable from C++ — read `displayText` (from: phase03_corefeat_20260827, 2026-08-27).
- e2e fake placement: put the fake at the SDK layer (FakeVieneu implementing the spike §0 surface) and run the REAL controller/worker/engine/QML/playback code — fake beside the controller re-tests the fake, not the wiring. Fake QMediaPlayers must implement the full duck-typed signal contract (`playbackStateChanged`/`mediaStatusChanged`/`errorOccurred`) — the playback wrapper connects them at construction (from: phase03_corefeat_20260827, 2026-08-27).
- Coverage survey BEFORE authoring new smoke/e2e suites: in phase04 all three chosen gaps were genuinely uncovered while four obvious candidates already had suites — author only what's missing (from: phase04_streaming_20260827, 2026-08-27).
- Real-model timing budget (offscreen CPU int8, warm HF cache): model lazy-load ≈ 1.0–1.8 s, first stream chunk ≈ 100 ms after call start (~45-char sentence; ×3 runs 99/101/102 ms) — AC-1's ~300 ms target met with ~3× margin on modern Apple Silicon. The older "load ≈30 s / sentence ≈3–8 s" figures were cold-page/pessimistic; size e2e timeouts by measured reality, keep generous margins for slower hosts. Seeded HF cache needs no network despite HF_TOKEN warning noise (from: phase03_corefeat_20260827; re-measured phase04_streaming_20260827).
- Offscreen REAL-mouse testing: `QTest.mouseClick` takes a QWindow, not an item — map item coordinates via `mapToScene()` plus the item's window; `findChildren(QQuickItem)` returns typed wrappers where geometry is method calls (`item.width()`), and QML class names from `metaObject().className()` carry a `_QML_NN` suffix, so match by prefix (`QQuickMouseArea`). Invoke QML signals with `QMetaObject.invokeMethod(item, "sig", Q_ARG("double", x))` — `real` params need `"double"`, `Q_ARG("QVariant", ...)` fails. If clicks land but nothing happens, recursively hit-test for a fullscreen overlay: a fake context property that is a plain Python attribute (no NOTIFY Property) reads `undefined`, so its `visible:` binding silently stays true and the scrim's MouseArea swallows every event (from: bead-driven waveform work a6r/yi5/56h, 2026-08-29).
- GitHub-hosted CI runner constraints: runners expose NO audio output device — skip asserts that require a real `QAudioSink` to drain (guard on a CI env marker) and rely on fakes/offscreen posture; and Windows imposes a subprocess ARGV length limit — keep subprocess smoke-driver command lines short and normalize path separators (`os.path` / `Path` on the Python side, never raw POSIX joins) or 22 tests fail Windows-only (from: commits 667f8e6 + 5e1b5e2, 2026-08-29).
- Merge same-function micro-tests instead of adding parameter rows (1029 → 872 items collected / 860 selected, 12 benchmark cases deselected, 2026-09-06…10; latest gate 859 passed + 1 skipped, commit 3eb6c90, 2026-09-10); benchmarks live behind `-m 'not benchmark'` (opt-in); smoke scenarios stay consolidated per subprocess driver (from: commits c0d5a52/9dad1cb/e43a1b6, 2026-09-06…10).
- SRT subtitle studio suites (2026-09-14): `tests/unit/test_subtitles.py` (cue parse/clean/re-emit), `test_align.py` (fit planning, speech units, rate caps), `test_subtitle_project.py` (store round-trip, fingerprint cache, streaming render), `test_subtitle_controller.py` (QML-facing controller), plus SRT scenarios in the shared `test_ui_tabs.py` smoke driver. Gate debt discovered at this refresh: the SRT commits left `ruff format --check .` RED — 7 files (`core/subtitles.py`, `ui/subtitle_controller.py`, and 5 test files); fixed in the same refresh's `style:` commit (658c564, bead c90), after which `ruff check .` + `ruff format --check .` pass and the suite ran 1023 passed + 1 skipped (one pre-existing intermittent: `TestStreamLifecycleSmoke::test_stream_bindings_e2e_cancel_cross_tab_and_error_recovery` — the `stream_cancel` `no_audio_retained` assert flakes under a loaded `-n auto` run and passes in isolation). LESSON: run `ruff format` (not just `ruff check`) before committing a new module+suite — the gate is `format --check` (from: commit 2068d8d + refresh 2026-09-14).
- A real-`QAudioSink` "drained the buffer" assert must guard on DEVICE ABSENCE, not just on `start()` failing: on the 2026-09-16 refresh `test_stream_playback.py::TestRealQtSmoke::test_real_qaudiosink_offscreen_smoke` failed `assert controller._io.bytesAvailable() == 0` (`19200 == 0`) while passing in isolation — it fails whenever it shares a run with ≥2 unit files, SERIALLY too (`-n 0`), because a device-less host constructs the ffmpeg sink "successfully" (logging only `QtWarningMsg: No audio device detected`) and never drains. The `skipif(CI == "true")` marker covers CI but the local guard only skips on a raise/`errorText`. Treat "sink exists but never drains" as environment-dependent (skip on no default output device, or on a bounded pump loop that does not reach 0) — the same family as the CI-runner constraint above (from: refresh 2026-09-16, bead VieNeuTTSApp-3iy).
- Suite size is a MOVING number — quote it with a date and the exact selection flags: 1055 collected / 1054 selected (12 benchmark deselected via `-m 'not benchmark'`, 2026-09-16); before the 2026-09-15 Studio consolidation it was 1036/1024, and 872/860 after the 2026-09-06…10 merge. Documented counts go stale fast; re-derive with `pytest --collect-only -q` instead of trusting prose (from: refresh 2026-09-16).
- Fake-host coverage of a subprocess engine (2026-09-21, `qwen_multiengine_20260920`): the scripted host logs only the frames it RECEIVED, so assert the ordered received list per host build, not "what we sent"; a crashed host's pid still answers `os.kill(pid, 0)` (zombie) until the engine's `close()`/`wait()` reaps it, so check reaping AFTER the close (and wait bounded before judging liveness); the host's pid is only public through its `starting` stderr line inside a 20-line tail, so read it right after `initialize()`; and a scenario that needs the RESTARTED host to behave differently must spawn the fake through a wrapper that reads its mode from a file, because the engine re-spawns the same command (from: commits 328baf5/9d52d1b, 2026-09-21).
- SIGPIPE belongs to the PROCESS, not the write (2026-09-21): `vienetts_app._restore_default_sigpipe()` sets `SIGPIPE` to `SIG_DFL` process-wide whenever the app's stdout is a pipe, so a plain `write()` to a dead child's stdin kills the whole app (observed as driver exit `-13`; pytest captures stdout with a pipe, a file-backed stdout hides it). Guard writes to a child pipe with `signal.pthread_sigmask` (block for the writing thread) + `signal.sigtimedwait` (consume a pending signal) and raise the actionable error instead — POSIX-only, gate on `hasattr(signal, "SIGPIPE")` (from: commit 328baf5, 2026-09-21).
- Second-controller e2e wiring: a flow that drives TWO controllers of the same kind (the audiobook sessions) must inject the SAME recording `PlaybackController` into both — the default factory builds a real `QMediaPlayer`, so the second session's resume-seek lands on an unobserved player and the assertion silently never fires (from: audiobook_epub_20260828, archived 2026-09-21).
---

Last refreshed: 2026-09-24 (**v0.2.0 released**) — the optional isolated Qwen 0.6B CustomVoice/Base engines and their **GGUF** format variant shipped: one capability table + `EngineState.qml` derivation + `submission_context_for()` gate, isolated model-host subprocesses with lazy restart and SIGPIPE-safe writes, verified runtime/model installs with offline-pack import and shared model files, engine- and variant-stamped provenance across artifacts/caches/Studio, profile-scoped clones, and the two-tier validation story (deterministic fake hosts in CI, opt-in real-model release smoke — `linux-x64-cpu` is the only probe-verified GGUF cell, the other five stay `pending`). deps unchanged vieneu 3.3.0/PySide6 6.11.2/pypdf 6.16.2, no pyproject/uv.lock drift (the Qwen stack lives only in the managed runtime); test items 2263 collected / 2251 selected (12 benchmark deselected); gate = ruff check + format --check green (192 files), pytest 2262 passed + 1 device-dependent real-`QAudioSink` skip; conductor tracks: 4 archived, `qwen_gguf_engine_20260923` still `[~]`
