"""Stateful streaming resampler shared by the Qwen model hosts.

Qwen emits native-rate audio (24 kHz) while the artifact writer and the live
transport expect the app rate (48 kHz) mono float32. Resampling each chunk
independently would restart the interpolation phase at every boundary
(clicks); :class:`StreamingResampler` carries the last input sample plus the
fractional output position across :meth:`push` calls, so a chunked stream
matches a one-shot resample. NumPy-only (scipy is not a project dependency)
so both the official host and the native GGUF host can share it.
"""

from __future__ import annotations

import numpy as np

from vienetts_app.core.engine_profiles import APP_SAMPLE_RATE


class StreamingResampler:
    """Linear-interpolation resampler carrying state across chunk pushes.

    Qwen emits native-rate audio (24 kHz) while the artifact writer and the live
    transport expect 48 kHz mono float32. Resampling each chunk independently
    would restart the interpolation phase at every boundary (clicks); this class
    carries the last input sample plus the fractional output position across
    :meth:`push` calls, so a chunked stream matches a one-shot resample.

    Output length for N total input samples is ``floor((N - 1) * dst / src) + 1``
    — within one output sample of the ideal duration. NumPy-only (scipy is not a
    project dependency).
    """

    def __init__(self, src_rate: int, dst_rate: int = APP_SAMPLE_RATE) -> None:
        if not isinstance(src_rate, int) or isinstance(src_rate, bool) or src_rate <= 0:
            raise ValueError(f"src_rate must be a positive int, got {src_rate!r}")
        if not isinstance(dst_rate, int) or isinstance(dst_rate, bool) or dst_rate <= 0:
            raise ValueError(f"dst_rate must be a positive int, got {dst_rate!r}")
        self._src_rate = src_rate
        self._dst_rate = dst_rate
        self._step = src_rate / dst_rate  # input samples per output sample
        self._carry: np.ndarray = np.zeros(0, dtype=np.float32)
        self._pos = 0.0  # input position of the next output sample

    @property
    def src_rate(self) -> int:
        return self._src_rate

    @property
    def dst_rate(self) -> int:
        return self._dst_rate

    def push(self, chunk: np.ndarray) -> np.ndarray:
        """Resample one native-rate chunk; empty input yields empty output."""
        data = _as_mono_float32(chunk)
        if self._src_rate == self._dst_rate:
            out = np.concatenate([self._carry, data]) if self._carry.size else data.copy()
            self._carry = np.zeros(0, dtype=np.float32)
            self._pos = 0.0
            return out
        window = np.concatenate([self._carry, data]) if self._carry.size else data
        if window.size < 2:
            self._carry = window.copy()
            return np.zeros(0, dtype=np.float32)
        # Emit every position <= window.size - 2: the final in-window position
        # has no right neighbour yet and more input may still arrive (flush
        # emits it). Positions are generated by multiplication, not repeated
        # addition — same values for the 2×/½× ratios this resampler runs.
        positions = _positions(self._pos, self._step, window.size - 2)
        out = _interpolate(window, positions)
        # Keep every input sample at or after the last emitted pair's left index:
        # unconsumed input plus the one-sample overlap that keeps continuity.
        consumed = int(positions[-1]) if positions.size else 0
        keep_from = max(consumed, 0)
        self._carry = window[keep_from:].copy()
        self._pos = self._pos + positions.size * self._step - keep_from
        return out

    def flush(self) -> np.ndarray:
        """Emit the tail sample(s) up to the final input position."""
        if self._src_rate == self._dst_rate:
            out = self._carry
            self._carry = np.zeros(0, dtype=np.float32)
            self._pos = 0.0
            return out
        window = self._carry
        if window.size == 0:
            return np.zeros(0, dtype=np.float32)
        positions = _positions(self._pos, self._step, window.size - 1)
        out = _interpolate(window, positions)
        self._carry = np.zeros(0, dtype=np.float32)
        self._pos = 0.0
        return out

    def reset(self) -> None:
        """Drop carried state (cancellation / new job)."""
        self._carry = np.zeros(0, dtype=np.float32)
        self._pos = 0.0


def _as_mono_float32(chunk: np.ndarray) -> np.ndarray:
    if not isinstance(chunk, np.ndarray):
        raise ValueError(f"chunk must be a numpy array, got {type(chunk).__name__}")
    if chunk.ndim != 1:
        raise ValueError(f"chunk must be 1-D mono, got {chunk.ndim} dimensions")
    out = chunk.astype(np.float32, copy=False)
    if not np.all(np.isfinite(out)):
        raise ValueError("chunk must be finite")
    return out


def _positions(start: float, step: float, limit: float) -> np.ndarray:
    """Output positions ``start + k * step`` for every value ``<= limit``.

    Vectorized form of the old per-sample accumulation loop (one Python
    iteration per output sample — ~4 ms per audio-second): the values are
    identical for the exact binary ratios the resampler runs (0.5×/1×/2×), and
    the ``<= limit`` mask reproduces the loop's emission rule exactly. Never
    returns a position past ``limit``, so ``_interpolate``'s clamped right
    neighbour stays in bounds.
    """
    count = int((limit - start) / step) + 2
    if count <= 0:
        return np.zeros(0, dtype=np.float64)
    candidates = start + np.arange(count, dtype=np.float64) * step
    return candidates[candidates <= limit]


def _interpolate(window: np.ndarray, positions: np.ndarray) -> np.ndarray:
    if positions.size == 0:
        return np.zeros(0, dtype=np.float32)
    left = np.floor(positions).astype(np.int64)
    frac = (positions - left).astype(np.float32)
    right = np.minimum(left + 1, window.size - 1)
    return ((1.0 - frac) * window[left] + frac * window[right]).astype(np.float32)
